name: Build Windows

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          cache: true

      - name: Disable Analytics
        run: flutter --disable-analytics

      - name: Get dependencies
        run: flutter pub get

      - name: Prepare Windows Build
        # Directly generate the Windows build files with the correct generator
        # before running the full build command.
        run: |
          mkdir -p build/windows
          cmake -S windows -B build/windows -G "Visual Studio 17 2022"

      - name: Build Windows
        # Now that we've set the generator, this should pick up the existing build configuration.
        run: flutter build windows --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: cs-price-scanner-windows
          path: build/windows/runner/Release/
